### ISSUE TITLE
Not identify the area of the plate, which is the problem

### ISSUE THREAD

**Issue by walterog19** [oskopek/javaanpr#22]
Hi I try to include the image but does not identify the area of the plate.

![test11](https://cloud.githubusercontent.com/assets/16470085/12028352/078b2226-ada4-11e5-9049-898cec55b174.jpg)
![testp](https://cloud.githubusercontent.com/assets/16470085/12028354/1136dd06-ada4-11e5-88f2-50520e466330.jpg)

**Comment by oskopek** [comment]
Hello,

in situations like these, the report generator can often help. You can run it from the executable jar
`java -jar javaanpr.jar -recognize -i path_to_your_image.jpg -o report_directory/` or `mvn exec:java -Dexec.args="-recognize -i path_to_your_image.jpg -o report_directory/"`.

From the report
![screenshot from 2015-12-29 11-11-14](https://cloud.githubusercontent.com/assets/1811716/12032838/e867c2b8-ae1c-11e5-976e-b2ca377a36e6.png)

we can see that it (incorrectly) fixates on the brake lights, instead of on the plate in such a sunny and bright image. One solution is to crop them out (see image on the right). JavaANPR then detects the plate "TSZ452" with a correct `syntax.xml` setting, which is almost correct.

As to what you can do about it generally (without cropping) - you could try some pre-processing, for example lessening the brightness, normalizing the picture, etc... For example, using a threshold filter for brightness 250-255, I got the correct result: (not saying this is what you want to do in general, it depends on the camera, lighning, ...)

![screenshot from 2015-12-29 11-24-45](https://cloud.githubusercontent.com/assets/1811716/12033015/c92fe13a-ae1e-11e5-8d70-3351097d67af.png)

**Comment by oskopek** [comment]
Also, I think the plate in the second image is just too small for detection.

**Comment by walterog19** [comment]
Hi Oskoper thanks for  you answer , I try  to include  for   lessening the brightness  this code:

   RescaleOp rescaleOp = new RescaleOp(1.2f, 15, null);
            rescaleOp.filter( this.image,  this.image);  

And this fine  is much better.
I probe  other picture and  the  I identify by T   and 9 for 2,  i think this is for alphabets how train the neural red with other alphabet ?
Or this is because   bad config the sintax.xml
I config this :
  <type name="colombia">
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
 </type>
3 char and 3 number this is correct?

![test](https://cloud.githubusercontent.com/assets/16470085/12044529/e749200e-ae60-11e5-8291-f318b370c4cf.jpg)


Thanks.

**Comment by oskopek** [comment]
3 chars and 3 numbers seems ok, although there is no config in your comment.

As to the OCR not working, yes, you probably will have to train a new alphabet, because the current one (in `src/main/resources/alphabets`) is quite different (notably the `'I'` and `'9'` characters).

**Comment by walterog19** [comment]
Hi 
the  config in the sintaxis.xml is:

<?xml version="1.0" encoding="iso-8859-2"?>
<structure>
  <type name="colombia">
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="abcdefghijklmnopqrstuvwxyz"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
 </type>
</structure>

How to train  the  a new alphabet ?  I need replace  the picture in  .\resources\alphabets\alphabet_10x16_bw\i_10x16_bw.jpg  ?

**Comment by walterog19** [comment]
config  sintaxis.xml is:
![sintasix](https://cloud.githubusercontent.com/assets/16470085/12050598/8191b13a-aec5-11e5-864f-7baf0e7a4570.png)

**Comment by oskopek** [comment]
Take a look at the bachelor thesis of the original author:
http://javaanpr.sourceforge.net/anpr.pdf

It should be enough to put them in a similar directory and normalize them
via `-newalphabet`.
See the `-help` flag.


Best regards,

Ondrej Skopek

**Comment by oskopek** [comment]
Closing as wontfix.

**Comment by BVijayKrishna** [comment]
how to configure number of plates of **india** to recognize

```
<type name="india">
        <char content="abcdefghijklmno0pqrstuvwxyz"/>
        <char content="abcdefghijklmno0pqrstuvwxyz"/>
        <char content="abcdefghijklmno0pqrstuvwxyz"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
        <char content="0123456789"/>
    </type>
```

added this in syntax.xml but not working

**Comment by oskopek** [comment]
Please, do not cross post on old issues and into the mailing list - it won't help in getting your issue resolved quicker. Replied in #79.
